#!/bin/bash

# Guía para configurar Environments en Azure DevOps
# TP05 - Repuestera - Gestión de Aprobaciones

echo "🚀 Configuración de Environments para Repuestera"
echo "================================================"
echo ""
echo "⚠️  NOTA: Los environments deben crearse manualmente en Azure DevOps"
echo "    El CLI no soporta la creación de environments actualmente."
echo ""

# Variables del proyecto
PROJECT_NAME="tp05"
ORGANIZATION="mfrias42"
URL="https://dev.azure.com/$ORGANIZATION/$PROJECT_NAME/_environments"

echo "🔗 URL del proyecto: $URL"
echo ""
echo "📋 PASOS MANUALES REQUERIDOS:"
echo "================================"
echo ""
echo "1️⃣  Accede a Azure DevOps:"
echo "   $URL"
echo ""
echo "2️⃣  Crea los siguientes Environments:"
echo ""
echo "   📦 QA ENVIRONMENTS (Sin aprobación):"
echo "   ────────────────────────────────────"
echo "   • Nombre: qa-backend"
echo "   • Descripción: Backend QA Environment - Auto Deploy"
echo "   • Aprobaciones: Ninguna"
echo ""
echo "   • Nombre: qa-frontend"
echo "   • Descripción: Frontend QA Environment - Auto Deploy"
echo "   • Aprobaciones: Ninguna"
echo ""
echo "   🔐 PRODUCTION ENVIRONMENTS (Con aprobación):"
echo "   ──────────────────────────────────────────────"
echo "   • Nombre: production-backend"
echo "   • Descripción: Backend Production Environment - Manual Approval Required"
echo "   • Aprobaciones: ✅ CONFIGURAR (Ver paso 3)"
echo ""
echo "   • Nombre: production-frontend"
echo "   • Descripción: Frontend Production Environment - Manual Approval Required"
echo "   • Aprobaciones: ✅ CONFIGURAR (Ver paso 3)"
echo ""
echo "3️⃣  Configurar Aprobaciones para Production:"
echo "   ─────────────────────────────────────────"
echo "   Para cada Production Environment:"
echo "   a) Clic en el environment"
echo "   b) Ve a 'Approvals and checks'"
echo "   c) Clic en '+' → 'Approvals'"
echo "   d) Agrega approvers:"
echo "      - mfrias42@dev.azure.com (Principal)"
echo "      - [Otros según necesidad]"
echo "   e) Configuración recomendada:"
echo "      - Minimum approvers: 1"
echo "      - Allow requestor to approve: No"
echo "      - Timeout: 30 days"
echo ""
echo "4️⃣  Verificar configuración:"
echo "   ─────────────────────────"
echo "   • QA environments: Sin checks"
echo "   • Production environments: Con approval check"
echo ""
echo "✅ Una vez completado, el pipeline estará listo para:"
echo "   • Deploy automático a QA"
echo "   • Deploy con aprobación manual a Production"
echo ""
echo "📖 Documentación completa en:"
echo "   • APPROVAL_PROCESS.md"
echo "   • MANUAL_APPROVALS_SETUP.md"